# Generated by Django 5.1.4 on 2024-12-21 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_task_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='employee',
            new_name='employeer',
        ),
    ]
