# Generated by Django 5.1.4 on 2024-12-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_rename_employee_comment_employeer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='employeer',
        ),
    ]
