# Generated by Django 5.1.4 on 2024-12-21 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_remove_comment_employeer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
    ]
