# Generated by Django 5.1.4 on 2024-12-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_remove_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
    ]
