# # Generated by Django 5.1.4 on 2024-12-26 10:33

# import django.db.models.deletion
# from django.conf import settings
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('employees', '0009_employee_email_employee_first_name_and_more'),
#         migrations.swappable_dependency(settings.AUTH_USER_MODEL),
#     ]

#     operations = [
#         migrations.AddField(
#             model_name='comment',
#             name='author',
#             field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
#             preserve_default=False,
#         ),
#         migrations.AddField(
#             model_name='comment',
#             name='text',
#             field=models.TextField(default='text'),
#             preserve_default=False,
#         ),
#         migrations.AlterField(
#             model_name='employee',
#             name='email',
#             field=models.EmailField(max_length=355, unique=True),
#         ),
#     ]
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_email_employee_first_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                null=True,  # Allow null for existing records
            ),
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='text'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=355, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),  # No need to specify default manually
        ),
    ]

