# Generated by Django 5.1.4 on 2024-12-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_alter_task_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='employee',
        ),
    ]
