# Generated by Django 5.1.4 on 2024-12-30 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_alter_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='employee',
        ),
    ]
