# Generated by Django 5.1.4 on 2024-12-31 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0018_alter_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_at',
        ),
    ]
