# Generated by Django 5.1.4 on 2025-01-19 09:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0022_task_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reset_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
